info:
  name: lession-2-sms-interface
server:
  port: 9002

# 调用refresh的时候不校验权限
management:
  security:
    enabled: false
    
spring:
  rabbitmq:
    host: 192.168.1.101
    port: 5672
    username: guest
    password: '{cipher}20c45f5fb2c588bae51565ba7ea78a3d4cd0cc754805f3c65629eb64a5b6576c'

tony:
  configString: 这是开发环境--test
  devString: 开发环境特有的配置
redis:
  host: localhost
  port: 6379
